### ISSUE TITLE
ポストの文字列を普通に選択できるようにする

### ISSUE THREAD

**Issue by tockri** [tockri/taittsuu-support#3]
```css
.taittsuu-support-disable-post-link .post-content-wrapper>a.post-link {
  pointer-events: none;
}
.taittsuu-support-disable-post-link .post-content-wrapper>a.post-link a {
  pointer-events: auto;
}
```
でよさそう
